---
  - name: disable transparent huge pages
    template:
      src: thp-never.service.j2
      dest: /etc/systemd/system/thp-never.service
      mode: 0755
      owner: root
      group: root
    notify: disable transparent huge pages
