---
- name: cleanup
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '{{ redis_download_file }}'
    - '{{ redis_source_dir }}'

- name: download
  get_url:
    url: '{{ redis_archive_url }}'
    dest: '{{ redis_download_dir }}'
    checksum: '{{ redis_download_checksum }}'

- name: extract
  unarchive:
    src: '{{ redis_download_file }}'
    dest: '{{ redis_download_dir }}'
    remote_src: yes
